version: "3"
services:
  app:
    restart: always
    build: .
    command: >
      bash -c
      "python3 manage.py runserver_plus 0.0.0.0:443 --cert-file thuhelper.whiteffire.cn.pem"
    volumes:
      - .:/code
    expose:
      - "443"
    depends_on:
      - db
    networks:
      - web_network
      - db_network
    ports:
      - 443:443
  db:
    image: mysql:5.7
    volumes:
      - "./mysql:/var/lib/mysql"
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_DATABASE=THU_HELPER
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - db_network
    ports:
      - 3306:3306

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume:
